Demonstrate the need for a dynamic linker
Fails with
example/ts_lib/foo.ts(2,1): error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try 'npm i --save-dev @types/node'.